input_data_path: "data/raw/heart_cleveland.csv"
output_model_path: "models/catboost.pkl"
splitting_params:
  val_size: 0.2
  stratify: true
  random_state: 42
train_params:
  model_type: "CatBoost"
  evaluate_metrics:
    - 'accuracy'
    - 'f1'
    - 'recall'
    - 'roc_auc'
  random_state: 42
feature_params:
  categorical_features:
    - "sex"
    - "cp"
    - "fbs"
    - "restecg"
    - "exang"
    - "slope"
    - "ca"
    - "thal"
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
  target_col: "condition"

